extends: airbnb-base
parserOptions: 
  ecmaVersion: 6
  sourceType: module
env: 
  es6: true
  browser: true
  node: true
  mocha: true
rules:
  semi: [error,never]
  no-restricted-syntax: 0
  one-var: 0
  no-var: 0
  prefer-const: 0
  no-continue: 0
  no-underscore-dangle: 0
  one-var-declaration-per-line: 0
  no-param-reassign: 0
  no-use-before-define: 0
  guard-for-in: 0
  no-shadow: 0
  no-unused-vars: 0
  vars-on-top: 0
  linebreak-style: [0,"error","unix"]